### ISSUE TITLE
Google DMARC initiative. 

### ISSUE THREAD

**Issue by alekspickle** [dongri/mailgun-rs#1]
Hi! I tried to send gmail-to-gmail email but got this on mailgun dashboard.
```
Unauthenticated email from google.com is not accepted due to domain's DMARC policy. Please contact the administrator of google.com domain if this was a legitimate mail. Please visit https://support.google.com/mail/answer/2451690 to learn about the DMARC initiative. 
```

Any fix you can suggest?
Otherwise it's not particularly better, comparing to construct mailgun request with `Command` substitution...

**Comment by dongri** [comment]
@alekspickle 
Sorry, response late
No such problem occurred in my environment.
Can you post me a screenshot

<img width="1248" alt="Screen Shot 2020-02-24 at 22 16 52" src="https://user-images.githubusercontent.com/878993/75155452-6bc20180-5753-11ea-91dd-16f5f6f81c45.png">

**Comment by alekspickle** [comment]
Oh, man, I don't even remember what I was trying to do.
I guess we can assume it was me configuring something wrong.
