### ISSUE TITLE
Bumping Reqwest version

### ISSUE THREAD

**Issue by benjaminch** [dongri/mailgun-rs#3]
Hello there !
First of, thanks for this lib, it's very handy :)

I just created a PR https://github.com/dongri/mailgun-rs/pull/2 to bump `reqwest` version.
Having old reqwest version is causing some versions clashes eventually in downstream apps / libraries.

Thanks again :)

**Comment by dongri** [comment]
https://github.com/dongri/mailgun-rs/pull/2
Thank you! Merged

**Comment by benjaminch** [comment]
Thanks a lot 😉
