### ISSUE TITLE
Allow change the api url

### ISSUE THREAD

**Issue by xerenahmed** [dongri/mailgun-rs#9]
I've been having difficulty with posting to the API. It kept responding with a 'Forbidden' message, and nothing more. After some research, I discovered the reason: in my situation, the API endpoint should start with 'api.eu'.

> NOTE: If you’re sending from our EU infrastructure, be sure to substitute the beginning of the endpoint “https://api.mailgun.net” with “https://api.eu.mailgun.net”

from https://documentation.mailgun.com/en/latest/quickstart-sending.html#send-via-api:~:text=NOTE%3A%20If%20you%E2%80%99re%20sending%20from%20our%20EU%20infrastructure%2C%20be%20sure%20to%20substitute%20the%20beginning%20of%20the%20endpoint%20%E2%80%9Chttps%3A//api.mailgun.net%E2%80%9D%20with%20%E2%80%9Chttps%3A//api.eu.mailgun.net%E2%80%9D

**Comment by dongri** [comment]
@xerenahmed v1.0.10 
region can be specified
https://github.com/dongri/mailgun-rs/pull/10/files
